apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-rust
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/katopz/helloworld-rust
          env:
            - name: TARGET
              value: 'Rust Sample v1'
